# Generated by Django 5.0.3 on 2024-03-09 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('inscricoes', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('duracao', models.DurationField()),
                ('categoria', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('IN', 'Iniciante'), ('IT', 'Intermediário'), ('AV', 'Avançado')], max_length=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cursos_thumbnails/')),
                ('preco_creditos', models.PositiveIntegerField(default=1)),
                ('descricao_breve', models.CharField(blank=True, max_length=255)),
                ('idioma', models.CharField(max_length=50)),
                ('status', models.CharField(default='Ativo', max_length=100)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
